name: check_build
on: pull_request

jobs:
  documentation:
    name: Check Pull request
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - run: poetry install
      
      - run: |
          poetry run black --check src/saleor_app/
          poetry run isort --check src/saleor_app/
          poetry run flake8 src/saleor_app/

      - name: Run docs build test
        run: poetry run mkdocs build -s

      - name: Run unit tests
        run: |
          poetry run coverage erase
          poetry run coverage run --source="saleor_app" -p -m pytest src/saleor_app
          poetry run coverage combine
          poetry run coverage report --fail-under=90
