name: documentation
on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.10.2

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - run: poetry install

      - name: Deploy documentation
        run: |
          poetry run mkdocs gh-deploy --force
          poetry run mkdocs --version
